

const Data = {
  comments: [
    ["anna_w",           "Niee mozliwe 😭😭"],
    ["krzys99",          "piękna jesteś!!!"],
    ["zofia_m",          "obserwuję od początku i wow ❤️"],
    ["tomek_xd",         "HEJKA Z KRAKOWA"],
    ["user_basia",       "jakie oczy masz serio"],
    ["maciek1234",       "kiedy kolejny live?"],
    ["kinga.kk",         "twoja muzyka 😍😍"],
    ["patryk_yt",        "nie mogę przestać oglądać lol"],
    ["ola_smile",        "KOCHAM CIĘ 💜💜💜"],
    ["dawid__x",         "ile followersow masz? pytam serio"],
    ["julia.rose",       "to jest niesamowite"],
    ["bartosz99",        "hej z Warszawy!!!"],
    ["magda_official",   "twój styl to 10/10"],
    ["kamil_street",     "kiedy merch?"],
    ["werka2003",        "moja mama też ogląda haha"],
    ["filip_dev",        "ten live to złoto"],
    ["nadia_art",        "twoja muzyka zmienia moje życie ❤️"],
    ["roman_x",          "first time tu i wow"],
    ["monika99",         "nie wychodzę z tego live"],
    ["szymon_k",         "LECIMY 100K 🔥🔥🔥"],
    ["ala_kawaii",       "jaki telefon masz?"],
    ["piotr_f",          "świetny vibe tutaj"],
    ["kasia.m",          "obserwuję od 2021 ❤"],
    ["lucyna88",         "piękny stream"],
    ["radek_xd",         "hej mama oglądaj"],
    ["zuzia_art",        "twoje tańce są ponad wszystko"],
    ["marek_pro",        "kiedy tour?"],
    ["ewa_kawaii",       "nie wiem jak to możliwe że jesteś taka piękna"],
    ["igor_b",           "HEJKA"],
    ["celina22",         "stream bez końca pls 🙏"],
  ],

  avatarColors: [
    "linear-gradient(135deg,#e040fb,#7c4dff)",
    "linear-gradient(135deg,#4ecdc4,#44a08d)",
    "linear-gradient(135deg,#f7971e,#ffd200)",
    "linear-gradient(135deg,#ee0979,#ff6a00)",
    "linear-gradient(135deg,#11998e,#38ef7d)",
    "linear-gradient(135deg,#4776e6,#8e54e9)",
  ],
};
